"""
Build the Tayo Church Library V1 spreadsheet.

Produces tayo_church_library_v1.xlsx with one row per church.
Default verification_status = "Pending Verification"; the Tayo Team
account flips to "Verified" after their legitimacy check.

Rate / contact data is filled where verifiable from public sources.
Where not verifiable, rate_label = "Inquire with parish" (per
0006 spec convention) and contact fields are left blank.
"""

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from datetime import date

OUTPUT = "tayo_church_library_v1.xlsx"
TODAY = date.today().isoformat()

COLUMNS = [
    ("id", 8),
    ("name", 38),
    ("also_known_as", 28),
    ("denomination", 18),
    ("type", 16),
    ("heritage_status", 18),
    ("diocese", 28),
    ("archdiocese", 24),
    ("address", 36),
    ("city_municipality", 20),
    ("province", 18),
    ("region", 22),
    ("gps_lat", 11),
    ("gps_lng", 11),
    ("contact_phone", 22),
    ("contact_email", 28),
    ("contact_website", 36),
    ("wedding_rate_php", 18),
    ("rate_label", 26),
    ("rate_includes", 36),
    ("reservation_fee_php", 14),
    ("air_conditioned", 14),
    ("exterior_photo_source", 44),
    ("interior_photo_source", 44),
    ("source_urls", 44),
    ("verification_status", 22),
    ("verified_by_account", 22),
    ("verified_at", 14),
    ("last_updated", 14),
    ("notes", 40),
]

INQUIRE = "Inquire with parish"
PENDING = "Pending Verification"
PLACEHOLDER_ADMIN = ""  # Set by Tayo Team account on verification

def row(d):
    """Fill defaults for any missing columns."""
    base = {k: "" for k, _ in COLUMNS}
    base.update({
        "denomination": "Roman Catholic",
        "heritage_status": "None",
        "wedding_rate_php": "",
        "rate_label": INQUIRE,
        "air_conditioned": "Inquire",
        "verification_status": PENDING,
        "verified_by_account": PLACEHOLDER_ADMIN,
        "verified_at": "",
        "last_updated": TODAY,
    })
    base.update(d)
    return base


# ---------------------------------------------------------------------------
# DATA — organized by region, then by diocese. Add new entries by appending.
# Photo / source URLs prefer Wikipedia article pages (stable, host their own
# imagery) and the parish's official site or RCAM page where available.
# ---------------------------------------------------------------------------

DATA = []

# ===========================================================================
# NCR — Roman Catholic Archdiocese of Manila + suffragan dioceses
# ===========================================================================

DATA += [
    row({
        "id": "PH-NCR-001",
        "name": "Manila Cathedral - Basilica",
        "also_known_as": "Minor Basilica and Metropolitan Cathedral of the Immaculate Conception",
        "type": "Cathedral",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Cabildo cor. Beaterio St., Intramuros",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5917",
        "gps_lng": "120.9742",
        "contact_phone": "+63 (2) 8527-3093",
        "contact_website": "https://manilacathedral.com.ph",
        "wedding_rate_php": "32000-42000",
        "rate_label": "₱32,000–₱42,000",
        "rate_includes": "Air-con tier ₱42,000 includes chandelier lighting; non-AC ₱32,000",
        "reservation_fee_php": "10000",
        "air_conditioned": "Optional",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Manila_Cathedral",
        "interior_photo_source": "https://manilacathedral.com.ph/wedding_requirements",
        "source_urls": "https://manilacathedral.com.ph/wedding_requirements; https://dlweddingsforless.com/2025/04/14/the-ultimate-manila-cathedral-wedding-guide-exclusive-information-they-dont-want-you-to-know/",
        "notes": "Reservation online only. Full payment 2 months before. Confirm 2026 rate by phone.",
    }),
    row({
        "id": "PH-NCR-002",
        "name": "San Agustin Church",
        "also_known_as": "Immaculate Conception Parish, Intramuros",
        "type": "Minor Basilica",
        "heritage_status": "UNESCO World Heritage",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "General Luna St., Intramuros",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5887",
        "gps_lng": "120.9750",
        "contact_phone": "+63 938 131 1285",
        "contact_email": "sanagustinchurch1571@gmail.com",
        "wedding_rate_php": "27000",
        "rate_label": "₱27,000 stipend (+ ₱1,000 video electricity)",
        "rate_includes": "1-hour ceremony slot. ₱5,000 surcharge per 30-min overrun (subject to availability)",
        "reservation_fee_php": "15000",
        "air_conditioned": "No",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/San_Agustin_Church_(Manila)",
        "interior_photo_source": "https://en.wikipedia.org/wiki/San_Agustin_Church_(Manila)",
        "source_urls": "https://ouineseventscoordination.wordpress.com/2014/04/25/san-agustin-church-intramuros-manila-marriage-requirements/; https://dlweddingsforless.com/2024/09/23/planning-your-wedding-at-san-agustin-church-intramuros-heres-what-you-need-to-know/",
        "notes": "UNESCO heritage; one of four Baroque Churches of the Philippines inscribed 1993. Down payment non-refundable.",
    }),
    row({
        "id": "PH-NCR-003",
        "name": "Minor Basilica of San Sebastian",
        "also_known_as": "San Sebastian Church (all-steel)",
        "type": "Minor Basilica",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Plaza del Carmen, Quiapo",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5990",
        "gps_lng": "120.9886",
        "contact_phone": "+63 (2) 8734-8931 / +63 998 951 6484",
        "contact_email": "sansebastianparish@gmail.com",
        "contact_website": "https://www.rcam.org/sansebastianchurch/",
        "wedding_rate_php": "20000-24000",
        "rate_label": "₱20,000–₱24,000",
        "rate_includes": "Priest, mass, candles, red carpet, simple flower decor, ushers, soloist & organist",
        "air_conditioned": "No",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Basilica_of_San_Sebasti%C3%A1n",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Basilica_of_San_Sebasti%C3%A1n",
        "source_urls": "https://www.rcam.org/sansebastianchurch/contact-us/; https://ouineseventscoordination.wordpress.com/2020/04/19/san-sebastian-church-wedding-requirements/",
        "notes": "Only all-steel basilica in Asia. Confirm current package by phone.",
    }),
    row({
        "id": "PH-NCR-004",
        "name": "Minor Basilica of the Black Nazarene",
        "also_known_as": "Quiapo Church",
        "type": "Minor Basilica",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Plaza Miranda, Quiapo",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5979",
        "gps_lng": "120.9836",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Quiapo_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Quiapo_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Quiapo_Church",
        "notes": "Very busy parish (Black Nazarene devotion). Wedding slots limited.",
    }),
    row({
        "id": "PH-NCR-005",
        "name": "Minor Basilica of San Lorenzo Ruiz",
        "also_known_as": "Binondo Church",
        "type": "Minor Basilica",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Plaza San Lorenzo Ruiz, Binondo",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.6007",
        "gps_lng": "120.9747",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Binondo_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Binondo_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Binondo_Church",
        "notes": "Filipino-Chinese parish; popular for couples in Chinatown.",
    }),
    row({
        "id": "PH-NCR-006",
        "name": "Malate Catholic Church",
        "also_known_as": "Our Lady of Remedies Parish",
        "type": "Parish",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "M.H. del Pilar cor. Remedios St., Malate",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5708",
        "gps_lng": "120.9817",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Malate_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Malate_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Malate_Church",
    }),
    row({
        "id": "PH-NCR-007",
        "name": "Santa Cruz Parish",
        "also_known_as": "Our Lady of the Pillar",
        "type": "Parish",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Plaza Sta. Cruz",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.6005",
        "gps_lng": "120.9800",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Santa_Cruz_Church_(Manila)",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Santa_Cruz_Church_(Manila)",
        "source_urls": "https://en.wikipedia.org/wiki/Santa_Cruz_Church_(Manila)",
    }),
    row({
        "id": "PH-NCR-008",
        "name": "St. Joseph Parish - Las Piñas",
        "also_known_as": "Las Piñas Bamboo Organ Church",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Parañaque",
        "archdiocese": "Archdiocese of Manila",
        "address": "Padre Diego Cera Ave.",
        "city_municipality": "Las Piñas",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.4480",
        "gps_lng": "120.9809",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Las_Pi%C3%B1as_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Las_Pi%C3%B1as_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Las_Pi%C3%B1as_Church",
        "notes": "Home of the historic 200-year-old bamboo organ.",
    }),
    row({
        "id": "PH-NCR-009",
        "name": "Shrine of Mary, Queen of Peace",
        "also_known_as": "EDSA Shrine",
        "type": "National Shrine",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "EDSA cor. Ortigas Ave.",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5841",
        "gps_lng": "121.0567",
        "wedding_rate_php": "5000",
        "rate_label": "₱5,000",
        "rate_includes": "Officiating priest, air-conditioning, carpet",
        "air_conditioned": "Yes",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/EDSA_Shrine",
        "interior_photo_source": "https://en.wikipedia.org/wiki/EDSA_Shrine",
        "source_urls": "https://en.wikipedia.org/wiki/EDSA_Shrine",
        "notes": "Slots Wed/Fri/Sat only. Budget-friendly choice.",
    }),
    row({
        "id": "PH-NCR-010",
        "name": "Antipolo Cathedral",
        "also_known_as": "International Shrine of Our Lady of Peace and Good Voyage",
        "type": "Cathedral",
        "diocese": "Diocese of Antipolo",
        "archdiocese": "Archdiocese of Manila (suffragan)",
        "address": "Dela Paz St.",
        "city_municipality": "Antipolo",
        "province": "Rizal",
        "region": "Region IV-A (CALABARZON)",
        "gps_lat": "14.5887",
        "gps_lng": "121.1763",
        "contact_phone": "+63 (2) 571 7347",
        "wedding_rate_php": "5000",
        "rate_label": "₱5,000",
        "rate_includes": "Altar, carpet, candle, choir (no floral arrangement)",
        "reservation_fee_php": "1000",
        "air_conditioned": "No",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Antipolo_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Antipolo_Cathedral",
        "source_urls": "https://ouineseventscoordination.wordpress.com/2017/11/21/churches-wedding-requirements-of-the-antipolo-cathedral-formerly-our-lady-of-peace-and-good-voyage-shrine/",
        "notes": "First international shrine in PH (2011). Confirm current rate; sources from ~2020.",
    }),
    row({
        "id": "PH-NCR-011",
        "name": "Santo Domingo Church",
        "also_known_as": "National Shrine of Our Lady of La Naval de Manila",
        "type": "National Shrine",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "537 Quezon Ave., Sta. Mesa Heights",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.6291",
        "gps_lng": "121.0095",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Santo_Domingo_Church_(Quezon_City)",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Santo_Domingo_Church_(Quezon_City)",
        "source_urls": "https://en.wikipedia.org/wiki/Santo_Domingo_Church_(Quezon_City)",
    }),
    row({
        "id": "PH-NCR-012",
        "name": "Christ the King Parish",
        "type": "Parish",
        "diocese": "Diocese of Cubao",
        "archdiocese": "Archdiocese of Manila",
        "address": "112 Greenmeadows Ave.",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://www.facebook.com/CKMissionSeminary",
        "source_urls": "https://www.rcam.org",
    }),
    row({
        "id": "PH-NCR-013",
        "name": "National Shrine of the Sacred Heart",
        "also_known_as": "Sacred Heart Parish (Makati)",
        "type": "National Shrine",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "Sacred Heart St., San Antonio Village",
        "city_municipality": "Makati",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/National_Shrine_of_the_Sacred_Heart_(Makati)",
        "source_urls": "https://en.wikipedia.org/wiki/National_Shrine_of_the_Sacred_Heart_(Makati)",
    }),
    row({
        "id": "PH-NCR-014",
        "name": "Immaculate Conception Cathedral - Pasig",
        "also_known_as": "Pasig Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "Plaza Rizal",
        "city_municipality": "Pasig",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5723",
        "gps_lng": "121.0848",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Pasig_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Pasig_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Pasig_Cathedral",
    }),
    row({
        "id": "PH-NCR-015",
        "name": "Santuario de San Antonio",
        "type": "Parish",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "McKinley Rd., Forbes Park",
        "city_municipality": "Makati",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Santuario_de_San_Antonio_Parish",
        "source_urls": "https://en.wikipedia.org/wiki/Santuario_de_San_Antonio_Parish",
        "notes": "Popular high-end society wedding venue.",
    }),
    row({
        "id": "PH-NCR-016",
        "name": "Mary the Queen Parish",
        "type": "Parish",
        "diocese": "Diocese of Cubao",
        "archdiocese": "Archdiocese of Manila",
        "address": "Greenhills",
        "city_municipality": "San Juan",
        "province": "Metro Manila",
        "region": "NCR",
        "source_urls": "https://www.rcam.org",
    }),
    row({
        "id": "PH-NCR-017",
        "name": "Santuario de San Jose",
        "type": "Parish",
        "diocese": "Diocese of Cubao",
        "archdiocese": "Archdiocese of Manila",
        "address": "Greenhills",
        "city_municipality": "San Juan",
        "province": "Metro Manila",
        "region": "NCR",
        "source_urls": "https://www.rcam.org",
    }),
    row({
        "id": "PH-NCR-018",
        "name": "Don Bosco Parish - Makati",
        "also_known_as": "St. John Bosco Parish",
        "type": "Parish",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "A. Arnaiz Ave., San Lorenzo Village",
        "city_municipality": "Makati",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Don_Bosco_Parish_(Makati)",
        "source_urls": "https://en.wikipedia.org/wiki/Don_Bosco_Parish_(Makati)",
    }),
    row({
        "id": "PH-NCR-019",
        "name": "Santo Niño de Paz Greenbelt Chapel",
        "also_known_as": "Greenbelt Chapel",
        "type": "Parish",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "Greenbelt Park, Ayala Center",
        "city_municipality": "Makati",
        "province": "Metro Manila",
        "region": "NCR",
        "gps_lat": "14.5510",
        "gps_lng": "121.0214",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Greenbelt_Chapel",
        "source_urls": "https://en.wikipedia.org/wiki/Greenbelt_Chapel",
    }),
    row({
        "id": "PH-NCR-020",
        "name": "St. Andrew the Apostle Parish",
        "also_known_as": "Parañaque Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Parañaque",
        "archdiocese": "Archdiocese of Manila",
        "address": "Quirino Ave., La Huerta",
        "city_municipality": "Parañaque",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Para%C3%B1aque_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Para%C3%B1aque_Cathedral",
    }),
    row({
        "id": "PH-NCR-021",
        "name": "San Roque Cathedral",
        "also_known_as": "Caloocan Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Caloocan",
        "archdiocese": "Archdiocese of Manila",
        "city_municipality": "Caloocan",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Caloocan_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Caloocan_Cathedral",
    }),
    row({
        "id": "PH-NCR-022",
        "name": "Immaculate Conception Cathedral - Cubao",
        "also_known_as": "Cubao Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Cubao",
        "archdiocese": "Archdiocese of Manila",
        "address": "Lantana cor. Gen. Ataviado St., Cubao",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Cubao_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Cubao_Cathedral",
    }),
    row({
        "id": "PH-NCR-023",
        "name": "National Shrine of Our Lady of Lourdes",
        "type": "National Shrine",
        "diocese": "Diocese of Novaliches",
        "archdiocese": "Archdiocese of Manila",
        "address": "26 Kanlaon St., Sta. Mesa Heights",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/National_Shrine_of_Our_Lady_of_Lourdes_(Quezon_City)",
        "source_urls": "https://en.wikipedia.org/wiki/National_Shrine_of_Our_Lady_of_Lourdes_(Quezon_City)",
    }),
    row({
        "id": "PH-NCR-024",
        "name": "National Shrine of Our Lady of Guadalupe",
        "type": "National Shrine",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "Bernardino St., Guadalupe Viejo",
        "city_municipality": "Makati",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Guadalupe_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Guadalupe_Church",
    }),
    row({
        "id": "PH-NCR-025",
        "name": "Diocesan Shrine of Mt. Carmel",
        "also_known_as": "Mt. Carmel Shrine, New Manila",
        "type": "Diocesan Shrine",
        "diocese": "Diocese of Cubao",
        "archdiocese": "Archdiocese of Manila",
        "address": "Broadway Ave., New Manila",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Mount_Carmel_Shrine_(Quezon_City)",
        "source_urls": "https://en.wikipedia.org/wiki/Mount_Carmel_Shrine_(Quezon_City)",
    }),
    row({
        "id": "PH-NCR-026",
        "name": "Don Bosco Parish - Mandaluyong",
        "type": "Parish",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "address": "A. Pichon St., Plainview",
        "city_municipality": "Mandaluyong",
        "province": "Metro Manila",
        "region": "NCR",
        "source_urls": "https://www.rcam.org",
    }),
    row({
        "id": "PH-NCR-027",
        "name": "Santuario de San Pedro Bautista",
        "type": "Parish",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "San Francisco del Monte",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/San_Pedro_Bautista_Church",
        "source_urls": "https://en.wikipedia.org/wiki/San_Pedro_Bautista_Church",
    }),
    row({
        "id": "PH-NCR-028",
        "name": "Holy Family Parish",
        "type": "Parish",
        "diocese": "Diocese of Cubao",
        "archdiocese": "Archdiocese of Manila",
        "address": "Roxas District",
        "city_municipality": "Quezon City",
        "province": "Metro Manila",
        "region": "NCR",
    }),
    row({
        "id": "PH-NCR-029",
        "name": "Mary Help of Christians Parish - Don Bosco Tondo",
        "type": "Parish",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Don Bosco Tondo",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
    }),
    row({
        "id": "PH-NCR-030",
        "name": "Sto. Niño de Tondo Parish",
        "type": "Parish",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Plaza Moriones, Tondo",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Sto._Ni%C3%B1o_de_Tondo_Parish",
        "source_urls": "https://en.wikipedia.org/wiki/Sto._Ni%C3%B1o_de_Tondo_Parish",
    }),
    row({
        "id": "PH-NCR-031",
        "name": "National Shrine of St. Therese of the Child Jesus",
        "type": "National Shrine",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "P. Burgos cor. Donada St.",
        "city_municipality": "Pasay",
        "province": "Metro Manila",
        "region": "NCR",
    }),
    row({
        "id": "PH-NCR-032",
        "name": "Our Lady of Loreto Parish",
        "type": "Parish",
        "diocese": "Archdiocese of Manila",
        "archdiocese": "Archdiocese of Manila",
        "address": "Bustillos, Sampaloc",
        "city_municipality": "Manila",
        "province": "Metro Manila",
        "region": "NCR",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Our_Lady_of_Loreto_Parish_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Our_Lady_of_Loreto_Parish_Church",
    }),
    row({
        "id": "PH-NCR-033",
        "name": "Our Lady of the Most Holy Rosary Parish - Pateros",
        "type": "Parish",
        "diocese": "Diocese of Pasig",
        "archdiocese": "Archdiocese of Manila",
        "city_municipality": "Pateros",
        "province": "Metro Manila",
        "region": "NCR",
    }),
    row({
        "id": "PH-NCR-034",
        "name": "Our Lady of Atocha Parish",
        "type": "Parish",
        "diocese": "Diocese of Parañaque",
        "archdiocese": "Archdiocese of Manila",
        "address": "Alabang",
        "city_municipality": "Muntinlupa",
        "province": "Metro Manila",
        "region": "NCR",
    }),
    row({
        "id": "PH-NCR-035",
        "name": "St. Jerome Emiliani and Sta. Susana Parish",
        "type": "Parish",
        "diocese": "Diocese of Parañaque",
        "archdiocese": "Archdiocese of Manila",
        "address": "Alabang Hills Village",
        "city_municipality": "Muntinlupa",
        "province": "Metro Manila",
        "region": "NCR",
    }),
]

# ===========================================================================
# CALABARZON & Central Luzon
# ===========================================================================

DATA += [
    row({
        "id": "PH-CAV-001",
        "name": "Our Lady of the Pillar Cathedral",
        "also_known_as": "Imus Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Imus",
        "archdiocese": "Archdiocese of Manila",
        "city_municipality": "Imus",
        "province": "Cavite",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Imus_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Imus_Cathedral",
    }),
    row({
        "id": "PH-CAV-002",
        "name": "Sta. Maria Magdalena Parish - Kawit",
        "type": "Parish",
        "heritage_status": "National Historical Landmark",
        "diocese": "Diocese of Imus",
        "archdiocese": "Archdiocese of Manila",
        "city_municipality": "Kawit",
        "province": "Cavite",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Kawit_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Kawit_Church",
    }),
    row({
        "id": "PH-CAV-003",
        "name": "Caleruega Church",
        "also_known_as": "Transfiguration Chapel at Caleruega",
        "type": "Chapel",
        "diocese": "Diocese of Imus",
        "archdiocese": "Archdiocese of Manila",
        "address": "Brgy. Kaylaway, Batulao",
        "city_municipality": "Nasugbu",
        "province": "Batangas",
        "region": "Region IV-A (CALABARZON)",
        "gps_lat": "14.0852",
        "gps_lng": "120.7178",
        "wedding_rate_php": "10000-15000",
        "rate_label": "₱10,000 off-peak / ₱15,000 peak (Dec 1–Jan 31)",
        "rate_includes": "Sound system, organ, CD player, sacristan. SAPP processing fee ₱7,000 separate. AC optional ₱5,000. Priest stipend at couple's discretion.",
        "air_conditioned": "Optional",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Caleruega",
        "interior_photo_source": "https://townsdelight.com/caleruega-church-a-complete-wedding-guide/",
        "source_urls": "https://townsdelight.com/caleruega-church-a-complete-wedding-guide/; https://www.yodisphere.com/2024/05/caleruega-church-wedding-complete-guide.html",
        "notes": "Operated by the Dominican Province of the Philippines. Very popular destination wedding spot with mountain views.",
    }),
    row({
        "id": "PH-CAV-004",
        "name": "Pink Sisters Convent Chapel - Tagaytay",
        "also_known_as": "Holy Spirit Sisters - Our Lady of Lourdes",
        "type": "Chapel",
        "diocese": "Diocese of Imus",
        "archdiocese": "Archdiocese of Manila",
        "city_municipality": "Tagaytay",
        "province": "Cavite",
        "region": "Region IV-A (CALABARZON)",
        "notes": "Popular Tagaytay wedding chapel — confirm if currently accepting weddings.",
    }),
    row({
        "id": "PH-BAT-001",
        "name": "Basilica of St. Martin de Tours",
        "also_known_as": "Taal Basilica",
        "type": "Minor Basilica",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of Lipa",
        "archdiocese": "Archdiocese of Lipa",
        "address": "St. Martin St.",
        "city_municipality": "Taal",
        "province": "Batangas",
        "region": "Region IV-A (CALABARZON)",
        "gps_lat": "13.8794",
        "gps_lng": "120.9281",
        "wedding_rate_php": "22000",
        "rate_label": "~₱22,000 (verify current)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Taal_Basilica",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Taal_Basilica",
        "source_urls": "https://en.wikipedia.org/wiki/Taal_Basilica; https://www.facebook.com/parokyanisanmartin/",
        "notes": "One of the largest Catholic churches in Asia. Rate from 2019 — confirm via FB.",
    }),
    row({
        "id": "PH-BAT-002",
        "name": "San Sebastian Cathedral - Lipa",
        "type": "Cathedral",
        "diocese": "Archdiocese of Lipa",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Lipa",
        "province": "Batangas",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Lipa_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Lipa_Cathedral",
    }),
    row({
        "id": "PH-BAT-003",
        "name": "Immaculate Conception Cathedral - Batangas City",
        "type": "Cathedral",
        "diocese": "Archdiocese of Lipa",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Batangas City",
        "province": "Batangas",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Batangas_City",
    }),
    row({
        "id": "PH-LAG-001",
        "name": "St. John the Baptist Parish - Calamba",
        "also_known_as": "Calamba Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of San Pablo",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Calamba",
        "province": "Laguna",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Calamba_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Calamba_Cathedral",
        "notes": "Site of José Rizal's baptism.",
    }),
    row({
        "id": "PH-LAG-002",
        "name": "St. Pedro de Alcantara Parish - Pakil",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of San Pablo",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Pakil",
        "province": "Laguna",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Pakil_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Pakil_Church",
    }),
    row({
        "id": "PH-LAG-003",
        "name": "St. Anthony of Padua Parish - Pila",
        "type": "Parish",
        "diocese": "Diocese of San Pablo",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Pila",
        "province": "Laguna",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Pila_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Pila_Church",
    }),
    row({
        "id": "PH-LAG-004",
        "name": "St. Gregory the Great Parish - Majayjay",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of San Pablo",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Majayjay",
        "province": "Laguna",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Majayjay_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Majayjay_Church",
    }),
    row({
        "id": "PH-LAG-005",
        "name": "St. Bartholomew the Apostle Parish - Nagcarlan",
        "type": "Parish",
        "diocese": "Diocese of San Pablo",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Nagcarlan",
        "province": "Laguna",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Nagcarlan_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Nagcarlan_Church",
    }),
    row({
        "id": "PH-RIZ-001",
        "name": "San Geronimo Parish - Morong",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Antipolo",
        "archdiocese": "Archdiocese of Manila",
        "city_municipality": "Morong",
        "province": "Rizal",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Morong_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Morong_Church",
    }),
    row({
        "id": "PH-QUE-001",
        "name": "St. Ferdinand Cathedral - Lucena",
        "type": "Cathedral",
        "diocese": "Diocese of Lucena",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Lucena",
        "province": "Quezon",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Lucena_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Lucena_Cathedral",
    }),
    row({
        "id": "PH-QUE-002",
        "name": "St. Michael the Archangel Basilica - Tayabas",
        "type": "Minor Basilica",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Lucena",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Tayabas",
        "province": "Quezon",
        "region": "Region IV-A (CALABARZON)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Tayabas_Basilica",
        "source_urls": "https://en.wikipedia.org/wiki/Tayabas_Basilica",
    }),
    row({
        "id": "PH-BUL-001",
        "name": "Immaculate Conception Cathedral - Malolos",
        "also_known_as": "Malolos Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Malolos",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Malolos",
        "province": "Bulacan",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Malolos_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Malolos_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Malolos_Cathedral",
    }),
    row({
        "id": "PH-BUL-002",
        "name": "Barasoain Church",
        "also_known_as": "Our Lady of Mt. Carmel Parish",
        "type": "Parish",
        "heritage_status": "National Historical Landmark",
        "diocese": "Diocese of Malolos",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Malolos",
        "province": "Bulacan",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Barasoain_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Barasoain_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Barasoain_Church",
        "notes": "Site of the First Philippine Republic Congress.",
    }),
    row({
        "id": "PH-PAM-001",
        "name": "Metropolitan Cathedral of San Fernando",
        "type": "Cathedral",
        "diocese": "Archdiocese of San Fernando",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "San Fernando",
        "province": "Pampanga",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/San_Fernando_Cathedral_(Pampanga)",
        "source_urls": "https://en.wikipedia.org/wiki/San_Fernando_Cathedral_(Pampanga)",
    }),
    row({
        "id": "PH-PAM-002",
        "name": "St. James the Apostle Parish - Betis",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of San Fernando",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Guagua (Betis)",
        "province": "Pampanga",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Betis_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Betis_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Betis_Church",
        "notes": "Known as the 'Sistine Chapel of the Philippines' for ceiling murals.",
    }),
    row({
        "id": "PH-PAM-003",
        "name": "Holy Rosary Parish",
        "also_known_as": "Pisamban Maragul, Angeles",
        "type": "Parish",
        "diocese": "Archdiocese of San Fernando",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Angeles",
        "province": "Pampanga",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Holy_Rosary_Parish_Church_(Angeles)",
        "source_urls": "https://en.wikipedia.org/wiki/Holy_Rosary_Parish_Church_(Angeles)",
    }),
    row({
        "id": "PH-PAM-004",
        "name": "St. Peter Apostle Parish - Apalit",
        "also_known_as": "Apung Iru",
        "type": "Parish",
        "diocese": "Archdiocese of San Fernando",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Apalit",
        "province": "Pampanga",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Apalit_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Apalit_Church",
    }),
    row({
        "id": "PH-TAR-001",
        "name": "San Sebastian Cathedral - Tarlac",
        "type": "Cathedral",
        "diocese": "Diocese of Tarlac",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Tarlac City",
        "province": "Tarlac",
        "region": "Region III (Central Luzon)",
    }),
    row({
        "id": "PH-NUE-001",
        "name": "St. Nicholas of Tolentine Cathedral - Cabanatuan",
        "type": "Cathedral",
        "diocese": "Diocese of Cabanatuan",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Cabanatuan",
        "province": "Nueva Ecija",
        "region": "Region III (Central Luzon)",
    }),
    row({
        "id": "PH-ZAM-001",
        "name": "St. Augustine Cathedral - Iba",
        "type": "Cathedral",
        "diocese": "Diocese of Iba",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Iba",
        "province": "Zambales",
        "region": "Region III (Central Luzon)",
    }),
    row({
        "id": "PH-BTN-001",
        "name": "St. Joseph Cathedral - Balanga",
        "type": "Cathedral",
        "diocese": "Diocese of Balanga",
        "archdiocese": "Archdiocese of San Fernando",
        "city_municipality": "Balanga",
        "province": "Bataan",
        "region": "Region III (Central Luzon)",
    }),
]

# ===========================================================================
# Ilocos / Cordillera / Cagayan Valley
# ===========================================================================

DATA += [
    row({
        "id": "PH-PAN-001",
        "name": "Minor Basilica of Our Lady of the Rosary of Manaoag",
        "also_known_as": "Manaoag Church",
        "type": "Minor Basilica",
        "diocese": "Diocese of Lingayen-Dagupan",
        "archdiocese": "Archdiocese of Lingayen-Dagupan",
        "address": "Dagupan Highway",
        "city_municipality": "Manaoag",
        "province": "Pangasinan",
        "region": "Region I (Ilocos)",
        "gps_lat": "16.0432",
        "gps_lng": "120.4886",
        "contact_phone": "(075) 529-0132 / +63 995 514 9783 / +63 961 627 1727",
        "contact_website": "https://www.manaoagminorbasilica.org/",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Manaoag_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Manaoag_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Manaoag_Church; https://www.manaoagminorbasilica.org/",
        "notes": "Major Marian pilgrimage site; high wedding demand. Confirm rate by phone.",
    }),
    row({
        "id": "PH-PAN-002",
        "name": "Epiphany of the Lord Cathedral - Lingayen",
        "type": "Cathedral",
        "diocese": "Archdiocese of Lingayen-Dagupan",
        "archdiocese": "Archdiocese of Lingayen-Dagupan",
        "city_municipality": "Lingayen",
        "province": "Pangasinan",
        "region": "Region I (Ilocos)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Lingayen_Cathedral",
    }),
    row({
        "id": "PH-PAN-003",
        "name": "St. John the Evangelist Metropolitan Cathedral - Dagupan",
        "type": "Cathedral",
        "diocese": "Archdiocese of Lingayen-Dagupan",
        "archdiocese": "Archdiocese of Lingayen-Dagupan",
        "city_municipality": "Dagupan",
        "province": "Pangasinan",
        "region": "Region I (Ilocos)",
    }),
    row({
        "id": "PH-LUN-001",
        "name": "St. William Cathedral - San Fernando, La Union",
        "type": "Cathedral",
        "diocese": "Diocese of San Fernando de La Union",
        "archdiocese": "Archdiocese of Lingayen-Dagupan",
        "city_municipality": "San Fernando",
        "province": "La Union",
        "region": "Region I (Ilocos)",
    }),
    row({
        "id": "PH-INO-001",
        "name": "San Agustin Church - Paoay",
        "also_known_as": "Paoay Church",
        "type": "Parish",
        "heritage_status": "UNESCO World Heritage",
        "diocese": "Diocese of Laoag",
        "archdiocese": "Archdiocese of Nueva Segovia",
        "city_municipality": "Paoay",
        "province": "Ilocos Norte",
        "region": "Region I (Ilocos)",
        "gps_lat": "18.0598",
        "gps_lng": "120.5217",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Paoay_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Paoay_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Paoay_Church",
        "notes": "UNESCO heritage; one of four Baroque Churches inscribed 1993.",
    }),
    row({
        "id": "PH-INO-002",
        "name": "St. William's Cathedral - Laoag",
        "type": "Cathedral",
        "diocese": "Diocese of Laoag",
        "archdiocese": "Archdiocese of Nueva Segovia",
        "city_municipality": "Laoag",
        "province": "Ilocos Norte",
        "region": "Region I (Ilocos)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Laoag_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Laoag_Cathedral",
    }),
    row({
        "id": "PH-ISU-001",
        "name": "St. Paul Metropolitan Cathedral - Vigan",
        "type": "Cathedral",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of Nueva Segovia",
        "archdiocese": "Archdiocese of Nueva Segovia",
        "city_municipality": "Vigan",
        "province": "Ilocos Sur",
        "region": "Region I (Ilocos)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Vigan_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Vigan_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Vigan_Cathedral",
    }),
    row({
        "id": "PH-ISU-002",
        "name": "Nuestra Señora de la Asunción - Sta. Maria",
        "also_known_as": "Sta. Maria Church",
        "type": "Parish",
        "heritage_status": "UNESCO World Heritage",
        "diocese": "Archdiocese of Nueva Segovia",
        "archdiocese": "Archdiocese of Nueva Segovia",
        "city_municipality": "Santa Maria",
        "province": "Ilocos Sur",
        "region": "Region I (Ilocos)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Santa_Maria_Church_(Ilocos_Sur)",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Santa_Maria_Church_(Ilocos_Sur)",
        "source_urls": "https://en.wikipedia.org/wiki/Santa_Maria_Church_(Ilocos_Sur)",
        "notes": "UNESCO heritage. Hilltop fortress-church.",
    }),
    row({
        "id": "PH-BEN-001",
        "name": "Cathedral of Our Lady of Atonement - Baguio",
        "also_known_as": "Baguio Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Baguio",
        "archdiocese": "Archdiocese of Nueva Segovia",
        "address": "Cathedral Loop",
        "city_municipality": "Baguio",
        "province": "Benguet",
        "region": "CAR (Cordillera)",
        "gps_lat": "16.4123",
        "gps_lng": "120.5961",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Baguio_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Baguio_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Baguio_Cathedral",
        "notes": "Pink-colored landmark; very popular Baguio wedding venue.",
    }),
    row({
        "id": "PH-CAG-001",
        "name": "St. Peter Metropolitan Cathedral - Tuguegarao",
        "type": "Cathedral",
        "diocese": "Archdiocese of Tuguegarao",
        "archdiocese": "Archdiocese of Tuguegarao",
        "city_municipality": "Tuguegarao",
        "province": "Cagayan",
        "region": "Region II (Cagayan Valley)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Tuguegarao_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Tuguegarao_Cathedral",
    }),
    row({
        "id": "PH-CAG-002",
        "name": "Basilica Minore de Nuestra Señora de Piat",
        "type": "Minor Basilica",
        "diocese": "Archdiocese of Tuguegarao",
        "archdiocese": "Archdiocese of Tuguegarao",
        "city_municipality": "Piat",
        "province": "Cagayan",
        "region": "Region II (Cagayan Valley)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Piat_Basilica",
        "source_urls": "https://en.wikipedia.org/wiki/Piat_Basilica",
    }),
    row({
        "id": "PH-ISA-001",
        "name": "St. Ferdinand Cathedral - Ilagan",
        "type": "Cathedral",
        "diocese": "Diocese of Ilagan",
        "archdiocese": "Archdiocese of Tuguegarao",
        "city_municipality": "Ilagan",
        "province": "Isabela",
        "region": "Region II (Cagayan Valley)",
    }),
    row({
        "id": "PH-ISA-002",
        "name": "Sts. Matthias Parish - Tumauini",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Ilagan",
        "archdiocese": "Archdiocese of Tuguegarao",
        "city_municipality": "Tumauini",
        "province": "Isabela",
        "region": "Region II (Cagayan Valley)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Tumauini_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Tumauini_Church",
        "notes": "Distinct red-brick Baroque facade.",
    }),
    row({
        "id": "PH-AUR-001",
        "name": "San Luis Obispo de Tolosa Parish - Baler",
        "type": "Parish",
        "diocese": "Prelature of Infanta",
        "archdiocese": "Archdiocese of Lipa",
        "city_municipality": "Baler",
        "province": "Aurora",
        "region": "Region III (Central Luzon)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Baler_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Baler_Church",
    }),
]

# ===========================================================================
# Bicol Region (Region V)
# ===========================================================================

DATA += [
    row({
        "id": "PH-CSU-001",
        "name": "Naga Metropolitan Cathedral",
        "also_known_as": "St. John the Evangelist Cathedral",
        "type": "Cathedral",
        "diocese": "Archdiocese of Caceres",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Naga",
        "province": "Camarines Sur",
        "region": "Region V (Bicol)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Naga_Metropolitan_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Naga_Metropolitan_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Naga_Metropolitan_Cathedral",
    }),
    row({
        "id": "PH-CSU-002",
        "name": "Basilica Minore de Nuestra Señora de Peñafrancia",
        "type": "Minor Basilica",
        "diocese": "Archdiocese of Caceres",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Naga",
        "province": "Camarines Sur",
        "region": "Region V (Bicol)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Basilica_Minore_of_Our_Lady_of_Pe%C3%B1afrancia",
        "source_urls": "https://en.wikipedia.org/wiki/Basilica_Minore_of_Our_Lady_of_Pe%C3%B1afrancia",
    }),
    row({
        "id": "PH-ALB-001",
        "name": "St. Gregory the Great Cathedral - Legazpi",
        "type": "Cathedral",
        "diocese": "Diocese of Legazpi",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Legazpi",
        "province": "Albay",
        "region": "Region V (Bicol)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Legazpi_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Legazpi_Cathedral",
    }),
    row({
        "id": "PH-ALB-002",
        "name": "Our Lady of the Gate Parish - Daraga",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Legazpi",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Daraga",
        "province": "Albay",
        "region": "Region V (Bicol)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Daraga_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Daraga_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Daraga_Church",
        "notes": "Iconic view of Mt. Mayon from the church grounds.",
    }),
    row({
        "id": "PH-SOR-001",
        "name": "Sts. Peter and Paul Cathedral - Sorsogon",
        "type": "Cathedral",
        "diocese": "Diocese of Sorsogon",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Sorsogon",
        "province": "Sorsogon",
        "region": "Region V (Bicol)",
    }),
    row({
        "id": "PH-MAS-001",
        "name": "St. Anthony of Padua Cathedral - Masbate",
        "type": "Cathedral",
        "diocese": "Diocese of Masbate",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Masbate City",
        "province": "Masbate",
        "region": "Region V (Bicol)",
    }),
    row({
        "id": "PH-CAT-001",
        "name": "Immaculate Conception Cathedral - Virac",
        "type": "Cathedral",
        "diocese": "Diocese of Virac",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Virac",
        "province": "Catanduanes",
        "region": "Region V (Bicol)",
    }),
    row({
        "id": "PH-CNO-001",
        "name": "Our Lady of the Immaculate Conception Cathedral - Daet",
        "type": "Cathedral",
        "diocese": "Diocese of Daet",
        "archdiocese": "Archdiocese of Caceres",
        "city_municipality": "Daet",
        "province": "Camarines Norte",
        "region": "Region V (Bicol)",
    }),
]

# ===========================================================================
# Visayas
# ===========================================================================

DATA += [
    row({
        "id": "PH-CEB-001",
        "name": "Cebu Metropolitan Cathedral",
        "type": "Cathedral",
        "diocese": "Archdiocese of Cebu",
        "archdiocese": "Archdiocese of Cebu",
        "address": "Mabini cor. Burgos St.",
        "city_municipality": "Cebu City",
        "province": "Cebu",
        "region": "Region VII (Central Visayas)",
        "gps_lat": "10.2961",
        "gps_lng": "123.9028",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Cebu_Metropolitan_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Cebu_Metropolitan_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Cebu_Metropolitan_Cathedral",
    }),
    row({
        "id": "PH-CEB-002",
        "name": "Basilica Minore del Santo Niño",
        "type": "Minor Basilica",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of Cebu",
        "archdiocese": "Archdiocese of Cebu",
        "address": "Pilgrim's Center, Osmeña Blvd.",
        "city_municipality": "Cebu City",
        "province": "Cebu",
        "region": "Region VII (Central Visayas)",
        "gps_lat": "10.2941",
        "gps_lng": "123.9020",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Basilica_Minore_del_Santo_Ni%C3%B1o",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Basilica_Minore_del_Santo_Ni%C3%B1o",
        "source_urls": "https://en.wikipedia.org/wiki/Basilica_Minore_del_Santo_Ni%C3%B1o",
        "notes": "Oldest Roman Catholic church in the Philippines (est. 1565).",
    }),
    row({
        "id": "PH-CEB-003",
        "name": "Sta. Catalina de Alejandria Parish - Carcar",
        "type": "Parish",
        "diocese": "Archdiocese of Cebu",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Carcar",
        "province": "Cebu",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Carcar_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Carcar_Church",
    }),
    row({
        "id": "PH-CEB-004",
        "name": "St. Michael the Archangel Parish - Argao",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of Cebu",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Argao",
        "province": "Cebu",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Argao_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Argao_Church",
    }),
    row({
        "id": "PH-CEB-005",
        "name": "St. Patrick Parish - Boljoon",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Archdiocese of Cebu",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Boljoon",
        "province": "Cebu",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Boljoon_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Boljoon_Church",
    }),
    row({
        "id": "PH-CEB-006",
        "name": "Sacred Heart Parish - Cebu",
        "type": "Parish",
        "diocese": "Archdiocese of Cebu",
        "archdiocese": "Archdiocese of Cebu",
        "address": "D. Jakosalem St.",
        "city_municipality": "Cebu City",
        "province": "Cebu",
        "region": "Region VII (Central Visayas)",
    }),
    row({
        "id": "PH-BOH-001",
        "name": "St. Joseph the Worker Cathedral - Tagbilaran",
        "type": "Cathedral",
        "diocese": "Diocese of Tagbilaran",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Tagbilaran",
        "province": "Bohol",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Tagbilaran_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Tagbilaran_Cathedral",
    }),
    row({
        "id": "PH-BOH-002",
        "name": "Baclayon Church",
        "also_known_as": "La Purisima Concepcion de la Virgen Maria",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Tagbilaran",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Baclayon",
        "province": "Bohol",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Baclayon_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Baclayon_Church",
        "notes": "Damaged in 2013 earthquake; restored.",
    }),
    row({
        "id": "PH-BOH-003",
        "name": "St. Peter the Apostle Parish - Loboc",
        "type": "Parish",
        "heritage_status": "National Cultural Treasure",
        "diocese": "Diocese of Talibon",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Loboc",
        "province": "Bohol",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Loboc_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Loboc_Church",
    }),
    row({
        "id": "PH-BOH-004",
        "name": "Our Lady of the Assumption Parish - Dauis",
        "type": "Parish",
        "diocese": "Diocese of Tagbilaran",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Dauis",
        "province": "Bohol",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Dauis_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Dauis_Church",
    }),
    row({
        "id": "PH-NOR-001",
        "name": "St. Catherine of Alexandria Cathedral - Dumaguete",
        "type": "Cathedral",
        "diocese": "Diocese of Dumaguete",
        "archdiocese": "Archdiocese of Cebu",
        "city_municipality": "Dumaguete",
        "province": "Negros Oriental",
        "region": "Region VII (Central Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Dumaguete_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Dumaguete_Cathedral",
    }),
    row({
        "id": "PH-NOC-001",
        "name": "San Sebastian Cathedral - Bacolod",
        "type": "Cathedral",
        "diocese": "Diocese of Bacolod",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Bacolod",
        "province": "Negros Occidental",
        "region": "Region VI (Western Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/San_Sebastian_Cathedral_(Bacolod)",
        "source_urls": "https://en.wikipedia.org/wiki/San_Sebastian_Cathedral_(Bacolod)",
    }),
    row({
        "id": "PH-NOC-002",
        "name": "San Diego Pro-Cathedral - Silay",
        "type": "Pro-Cathedral",
        "diocese": "Diocese of Bacolod",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Silay",
        "province": "Negros Occidental",
        "region": "Region VI (Western Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/San_Diego_Pro-Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/San_Diego_Pro-Cathedral",
    }),
    row({
        "id": "PH-ILO-001",
        "name": "Jaro Metropolitan Cathedral",
        "also_known_as": "National Shrine of Our Lady of Candles",
        "type": "Cathedral",
        "diocese": "Archdiocese of Jaro",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Iloilo City",
        "province": "Iloilo",
        "region": "Region VI (Western Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Jaro_Cathedral",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Jaro_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Jaro_Cathedral",
    }),
    row({
        "id": "PH-ILO-002",
        "name": "Sto. Tomas de Villanueva Parish - Miag-ao",
        "also_known_as": "Miag-ao Church",
        "type": "Parish",
        "heritage_status": "UNESCO World Heritage",
        "diocese": "Archdiocese of Jaro",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Miagao",
        "province": "Iloilo",
        "region": "Region VI (Western Visayas)",
        "gps_lat": "10.6447",
        "gps_lng": "122.2356",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Miag-ao_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Miag-ao_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Miag-ao_Church",
        "notes": "UNESCO heritage. One of four Baroque Churches inscribed 1993.",
    }),
    row({
        "id": "PH-ILO-003",
        "name": "St. Anne Parish - Molo",
        "also_known_as": "Molo Church (Feminist Church)",
        "type": "Parish",
        "diocese": "Archdiocese of Jaro",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Iloilo City",
        "province": "Iloilo",
        "region": "Region VI (Western Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Molo_Church",
        "interior_photo_source": "https://en.wikipedia.org/wiki/Molo_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Molo_Church",
    }),
    row({
        "id": "PH-ILO-004",
        "name": "St. John of Sahagun Parish - Tigbauan",
        "type": "Parish",
        "diocese": "Archdiocese of Jaro",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Tigbauan",
        "province": "Iloilo",
        "region": "Region VI (Western Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Tigbauan_Church",
        "source_urls": "https://en.wikipedia.org/wiki/Tigbauan_Church",
    }),
    row({
        "id": "PH-ILO-005",
        "name": "Sta. Barbara Parish - Iloilo",
        "type": "Parish",
        "diocese": "Archdiocese of Jaro",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "Santa Barbara",
        "province": "Iloilo",
        "region": "Region VI (Western Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Santa_Barbara_Church_(Iloilo)",
        "source_urls": "https://en.wikipedia.org/wiki/Santa_Barbara_Church_(Iloilo)",
    }),
    row({
        "id": "PH-AKL-001",
        "name": "Sto. Niño Cathedral - Kalibo",
        "type": "Cathedral",
        "diocese": "Diocese of Kalibo",
        "archdiocese": "Archdiocese of Capiz",
        "city_municipality": "Kalibo",
        "province": "Aklan",
        "region": "Region VI (Western Visayas)",
    }),
    row({
        "id": "PH-CAP-001",
        "name": "Immaculate Conception Metropolitan Cathedral - Roxas",
        "type": "Cathedral",
        "diocese": "Archdiocese of Capiz",
        "archdiocese": "Archdiocese of Capiz",
        "city_municipality": "Roxas City",
        "province": "Capiz",
        "region": "Region VI (Western Visayas)",
    }),
    row({
        "id": "PH-ANT-001",
        "name": "St. Joseph the Worker Cathedral - San Jose",
        "type": "Cathedral",
        "diocese": "Diocese of San Jose de Antique",
        "archdiocese": "Archdiocese of Jaro",
        "city_municipality": "San Jose de Buenavista",
        "province": "Antique",
        "region": "Region VI (Western Visayas)",
    }),
    row({
        "id": "PH-LEY-001",
        "name": "Sto. Niño Church - Tacloban",
        "type": "Parish",
        "diocese": "Archdiocese of Palo",
        "archdiocese": "Archdiocese of Palo",
        "city_municipality": "Tacloban",
        "province": "Leyte",
        "region": "Region VIII (Eastern Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Sto._Ni%C3%B1o_Church_(Tacloban)",
    }),
    row({
        "id": "PH-LEY-002",
        "name": "Our Lady of the Assumption Cathedral - Palo",
        "type": "Cathedral",
        "diocese": "Archdiocese of Palo",
        "archdiocese": "Archdiocese of Palo",
        "city_municipality": "Palo",
        "province": "Leyte",
        "region": "Region VIII (Eastern Visayas)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Palo_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Palo_Cathedral",
    }),
    row({
        "id": "PH-SAM-001",
        "name": "Sts. Peter and Paul Cathedral - Calbayog",
        "type": "Cathedral",
        "diocese": "Diocese of Calbayog",
        "archdiocese": "Archdiocese of Palo",
        "city_municipality": "Calbayog",
        "province": "Samar",
        "region": "Region VIII (Eastern Visayas)",
    }),
    row({
        "id": "PH-SAM-002",
        "name": "Sts. Peter and Paul Cathedral - Catbalogan",
        "type": "Cathedral",
        "diocese": "Diocese of Calbayog",
        "archdiocese": "Archdiocese of Palo",
        "city_municipality": "Catbalogan",
        "province": "Samar",
        "region": "Region VIII (Eastern Visayas)",
    }),
    row({
        "id": "PH-ESA-001",
        "name": "Borongan Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Borongan",
        "archdiocese": "Archdiocese of Palo",
        "city_municipality": "Borongan",
        "province": "Eastern Samar",
        "region": "Region VIII (Eastern Visayas)",
    }),
    row({
        "id": "PH-BIL-001",
        "name": "Naval Cathedral",
        "type": "Cathedral",
        "diocese": "Diocese of Naval",
        "archdiocese": "Archdiocese of Palo",
        "city_municipality": "Naval",
        "province": "Biliran",
        "region": "Region VIII (Eastern Visayas)",
    }),
]

# ===========================================================================
# Mindanao
# ===========================================================================

DATA += [
    row({
        "id": "PH-DAV-001",
        "name": "San Pedro Cathedral - Davao",
        "type": "Cathedral",
        "diocese": "Archdiocese of Davao",
        "archdiocese": "Archdiocese of Davao",
        "address": "San Pedro St.",
        "city_municipality": "Davao City",
        "province": "Davao del Sur",
        "region": "Region XI (Davao)",
        "gps_lat": "7.0707",
        "gps_lng": "125.6131",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/San_Pedro_Cathedral_(Davao_City)",
        "interior_photo_source": "https://en.wikipedia.org/wiki/San_Pedro_Cathedral_(Davao_City)",
        "source_urls": "https://en.wikipedia.org/wiki/San_Pedro_Cathedral_(Davao_City)",
    }),
    row({
        "id": "PH-DAV-002",
        "name": "Sacred Heart Parish - Davao",
        "type": "Parish",
        "diocese": "Archdiocese of Davao",
        "archdiocese": "Archdiocese of Davao",
        "city_municipality": "Davao City",
        "province": "Davao del Sur",
        "region": "Region XI (Davao)",
    }),
    row({
        "id": "PH-DAV-003",
        "name": "Redemptorist Church - Davao",
        "also_known_as": "Our Lady of Perpetual Help",
        "type": "Parish",
        "diocese": "Archdiocese of Davao",
        "archdiocese": "Archdiocese of Davao",
        "city_municipality": "Davao City",
        "province": "Davao del Sur",
        "region": "Region XI (Davao)",
    }),
    row({
        "id": "PH-DAV-004",
        "name": "St. Nicholas Cathedral - Mati",
        "type": "Cathedral",
        "diocese": "Diocese of Mati",
        "archdiocese": "Archdiocese of Davao",
        "city_municipality": "Mati",
        "province": "Davao Oriental",
        "region": "Region XI (Davao)",
    }),
    row({
        "id": "PH-DAV-005",
        "name": "Christ the King Cathedral - Tagum",
        "type": "Cathedral",
        "diocese": "Diocese of Tagum",
        "archdiocese": "Archdiocese of Davao",
        "city_municipality": "Tagum",
        "province": "Davao del Norte",
        "region": "Region XI (Davao)",
    }),
    row({
        "id": "PH-MIS-001",
        "name": "St. Augustine Metropolitan Cathedral - Cagayan de Oro",
        "type": "Cathedral",
        "diocese": "Archdiocese of Cagayan de Oro",
        "archdiocese": "Archdiocese of Cagayan de Oro",
        "city_municipality": "Cagayan de Oro",
        "province": "Misamis Oriental",
        "region": "Region X (Northern Mindanao)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Cagayan_de_Oro_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Cagayan_de_Oro_Cathedral",
    }),
    row({
        "id": "PH-MIS-002",
        "name": "Immaculate Conception Cathedral - Ozamiz",
        "type": "Cathedral",
        "diocese": "Archdiocese of Ozamiz",
        "archdiocese": "Archdiocese of Ozamiz",
        "city_municipality": "Ozamiz",
        "province": "Misamis Occidental",
        "region": "Region X (Northern Mindanao)",
    }),
    row({
        "id": "PH-LDN-001",
        "name": "St. Michael the Archangel Cathedral - Iligan",
        "type": "Cathedral",
        "diocese": "Archdiocese of Ozamiz (suffragan: Iligan)",
        "archdiocese": "Archdiocese of Ozamiz",
        "city_municipality": "Iligan",
        "province": "Lanao del Norte",
        "region": "Region X (Northern Mindanao)",
    }),
    row({
        "id": "PH-BUK-001",
        "name": "St. Isidore the Worker Cathedral - Malaybalay",
        "type": "Cathedral",
        "diocese": "Diocese of Malaybalay",
        "archdiocese": "Archdiocese of Cagayan de Oro",
        "city_municipality": "Malaybalay",
        "province": "Bukidnon",
        "region": "Region X (Northern Mindanao)",
    }),
    row({
        "id": "PH-CAM-001",
        "name": "Immaculate Conception Cathedral - Cotabato",
        "type": "Cathedral",
        "diocese": "Archdiocese of Cotabato",
        "archdiocese": "Archdiocese of Cotabato",
        "city_municipality": "Cotabato City",
        "province": "Maguindanao del Norte",
        "region": "BARMM",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Cotabato_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Cotabato_Cathedral",
    }),
    row({
        "id": "PH-ZBO-001",
        "name": "Metropolitan Cathedral of the Immaculate Conception - Zamboanga",
        "type": "Cathedral",
        "diocese": "Archdiocese of Zamboanga",
        "archdiocese": "Archdiocese of Zamboanga",
        "city_municipality": "Zamboanga City",
        "province": "Zamboanga del Sur",
        "region": "Region IX (Zamboanga Peninsula)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Zamboanga_Cathedral",
        "source_urls": "https://en.wikipedia.org/wiki/Zamboanga_Cathedral",
    }),
    row({
        "id": "PH-ZBO-002",
        "name": "Fort Pilar Shrine",
        "also_known_as": "Our Lady of the Pillar",
        "type": "National Shrine",
        "diocese": "Archdiocese of Zamboanga",
        "archdiocese": "Archdiocese of Zamboanga",
        "city_municipality": "Zamboanga City",
        "province": "Zamboanga del Sur",
        "region": "Region IX (Zamboanga Peninsula)",
        "exterior_photo_source": "https://en.wikipedia.org/wiki/Fort_Pilar",
        "source_urls": "https://en.wikipedia.org/wiki/Fort_Pilar",
    }),
    row({
        "id": "PH-ZDN-001",
        "name": "Sta. Catalina Cathedral - Dipolog",
        "type": "Cathedral",
        "diocese": "Diocese of Dipolog",
        "archdiocese": "Archdiocese of Ozamiz",
        "city_municipality": "Dipolog",
        "province": "Zamboanga del Norte",
        "region": "Region IX (Zamboanga Peninsula)",
    }),
    row({
        "id": "PH-ZSI-001",
        "name": "Sta. Maria Cathedral - Pagadian",
        "type": "Cathedral",
        "diocese": "Diocese of Pagadian",
        "archdiocese": "Archdiocese of Ozamiz",
        "city_municipality": "Pagadian",
        "province": "Zamboanga del Sur",
        "region": "Region IX (Zamboanga Peninsula)",
    }),
    row({
        "id": "PH-AGS-001",
        "name": "St. Joseph Cathedral - Butuan",
        "type": "Cathedral",
        "diocese": "Diocese of Butuan",
        "archdiocese": "Archdiocese of Cagayan de Oro",
        "city_municipality": "Butuan",
        "province": "Agusan del Norte",
        "region": "Region XIII (Caraga)",
    }),
    row({
        "id": "PH-SUR-001",
        "name": "San Nicolas Cathedral - Surigao",
        "type": "Cathedral",
        "diocese": "Diocese of Surigao",
        "archdiocese": "Archdiocese of Cagayan de Oro",
        "city_municipality": "Surigao City",
        "province": "Surigao del Norte",
        "region": "Region XIII (Caraga)",
    }),
    row({
        "id": "PH-SCO-001",
        "name": "Christ the King Cathedral - Marbel",
        "type": "Cathedral",
        "diocese": "Diocese of Marbel",
        "archdiocese": "Archdiocese of Cotabato",
        "city_municipality": "Koronadal",
        "province": "South Cotabato",
        "region": "Region XII (SOCCSKSARGEN)",
    }),
    row({
        "id": "PH-GSN-001",
        "name": "Sts. Peter and Paul Cathedral - General Santos",
        "type": "Cathedral",
        "diocese": "Diocese of Marbel",
        "archdiocese": "Archdiocese of Cotabato",
        "city_municipality": "General Santos",
        "province": "South Cotabato",
        "region": "Region XII (SOCCSKSARGEN)",
    }),
]

# ===========================================================================
# Build the workbook
# ===========================================================================

def build():
    wb = Workbook()
    ws = wb.active
    ws.title = "Church Library V1"

    # Header
    header_font = Font(name="Arial", size=10, bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", start_color="1F4E78")
    header_align = Alignment(horizontal="left", vertical="center", wrap_text=True)
    thin = Side(border_style="thin", color="B7B7B7")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    for idx, (col_name, width) in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=1, column=idx, value=col_name)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_align
        cell.border = border
        ws.column_dimensions[get_column_letter(idx)].width = width

    ws.freeze_panes = "C2"
    ws.row_dimensions[1].height = 32

    # Body
    body_font = Font(name="Arial", size=10)
    body_align = Alignment(horizontal="left", vertical="top", wrap_text=True)
    pending_fill = PatternFill("solid", start_color="FFF4D6")  # warm yellow
    verified_fill = PatternFill("solid", start_color="D6F4E0")  # soft green
    heritage_font = Font(name="Arial", size=10, color="8B0000", bold=True)

    for ridx, rec in enumerate(DATA, start=2):
        for cidx, (col_name, _) in enumerate(COLUMNS, start=1):
            v = rec.get(col_name, "")
            cell = ws.cell(row=ridx, column=cidx, value=v)
            cell.font = body_font
            cell.alignment = body_align
            cell.border = border

            if col_name == "verification_status":
                if v == "Pending Verification":
                    cell.fill = pending_fill
                elif v == "Verified":
                    cell.fill = verified_fill

            if col_name == "heritage_status" and v and v != "None":
                cell.font = heritage_font

    # Set row heights
    for r in range(2, len(DATA) + 2):
        ws.row_dimensions[r].height = 60

    # README sheet
    readme = wb.create_sheet("README")
    readme.column_dimensions["A"].width = 110
    readme["A1"] = "Tayo Church Library V1 — README"
    readme["A1"].font = Font(name="Arial", size=14, bold=True)

    readme_text = [
        "",
        "Purpose",
        "  Seed dataset for the Ceremony Venue line in iteration 0006 (Vendors Management).",
        "  Couples will pick from this list when they add a 'Ceremony Venue' vendor in their event.",
        "  Long-term, this table is consumed by Supabase as `ph_churches` (read-only reference).",
        "",
        "Verification workflow",
        "  Every row defaults to verification_status = 'Pending Verification'.",
        "  The Tayo Team admin account reviews each church for legitimacy:",
        "    1. Confirms the parish exists and is currently conducting weddings.",
        "    2. Verifies contact info reaches the actual parish office.",
        "    3. Confirms the published rate is current (or marks rate_label = 'Inquire with parish').",
        "    4. Sets verification_status = 'Verified', verified_by_account = <admin email>, verified_at = <date>.",
        "  Future iteration: split this single admin role into sub-roles (rate_verifier, contact_verifier, photo_curator).",
        "",
        "Rate handling",
        "  PH parishes generally do NOT publish wedding rates. Default is 'Inquire with parish'.",
        "  When a rate IS published in a public source, we record the numeric range in wedding_rate_php",
        "  and a display string in rate_label, plus the source URL in source_urls.",
        "  All rates need re-verification by phone — sources are often 1–5 years old.",
        "",
        "Photo handling",
        "  exterior_photo_source and interior_photo_source point to a STABLE article URL (Wikipedia preferred)",
        "  where images can be viewed. We do NOT hotlink raw image URLs. The Tayo Team confirms the article",
        "  loads and shows the church before flipping verification_status to Verified.",
        "  For the Tayo app UI, we'll later license/permission curated images and replace these with R2 paths.",
        "",
        "Coverage",
        "  V1 is aspirational nationwide — every diocese in PH is represented by at least its cathedral.",
        "  Major heritage churches (UNESCO + National Cultural Treasure) included with priority.",
        "  Popular wedding venues (Manaoag, Caleruega, Taal, EDSA Shrine, Antipolo, San Agustin, Manila Cathedral) included with rates.",
        "  Long tail (every parish in PH, ~3,000+) is NOT covered — not realistic for V1, and not used by typical couples.",
        "",
        "Adding new entries",
        "  Append a new row at the bottom. Required: id, name, diocese, archdiocese, city_municipality, province, region.",
        "  Use ID format: PH-<provincecode>-<3digit>. Province codes: NCR, CAV, BAT, LAG, RIZ, QUE, BUL, PAM, TAR, NUE,",
        "    ZAM, BTN, PAN, LUN, INO, ISU, BEN, CAG, ISA, AUR, CSU, ALB, SOR, MAS, CAT, CNO,",
        "    CEB, BOH, NOR, NOC, ILO, AKL, CAP, ANT, LEY, SAM, ESA, BIL, DAV, MIS, LDN, BUK, CAM,",
        "    ZBO, ZDN, ZSI, AGS, SUR, SCO, GSN.",
        "",
        "Schema mapping (when seeded into Supabase)",
        "  id              → ph_churches.code (PK, text)",
        "  name            → ph_churches.name",
        "  type            → ph_churches.kind (enum)",
        "  diocese         → ph_churches.diocese",
        "  city_municipality + province + region → ph_churches.location_*",
        "  gps_lat/lng     → ph_churches.geog (POINT)",
        "  contact_*       → ph_churches.contact_*",
        "  wedding_rate_php → ph_churches.published_rate_php (nullable)",
        "  exterior_photo_source / interior_photo_source → ph_churches.photo_source_*",
        "  verification_status → ph_churches.verification_status",
        "  verified_by_account → users.id (FK; users.is_tayo_admin = true)",
        "",
        "Last updated: " + TODAY,
    ]
    for i, line in enumerate(readme_text, start=2):
        c = readme.cell(row=i, column=1, value=line)
        c.font = Font(name="Arial", size=10, bold=line in (
            "Purpose", "Verification workflow", "Rate handling", "Photo handling",
            "Coverage", "Adding new entries", "Schema mapping (when seeded into Supabase)"))
        c.alignment = Alignment(wrap_text=True, vertical="top")

    wb.save(OUTPUT)
    print(f"Wrote {OUTPUT} with {len(DATA)} church entries.")


if __name__ == "__main__":
    build()
